--!strict

-- Connection-coverage audit over sets/audit_parts.txt (generated by
-- scripts on the python side). Only runs when sets/audit_enable.txt
-- exists, so normal test runs skip it. Output: one AUDIT| line per part
-- for offline analysis.

local TestTypes = require(script.Parent.Parent.Parent.TestTypes)
local LDrawLibrary = require(script.Parent.LDrawLibrary)
local flattenMesh = require(script.Parent.flattenMesh)
local findConnections = require(script.Parent.findConnections)
local deriveSockets = require(script.Parent.deriveSockets)

return function(t: TestTypes.TestContext)
	t.test("audit connection coverage", function()
		if t.readFile("sets/audit_enable.txt") == nil then
			t.log("audit skipped (no sets/audit_enable.txt)")
			return
		end
		local listing = t.readFile("sets/audit_parts.txt")
		if listing == nil then
			t.fail("sets/audit_parts.txt missing")
			return
		end

		local library = LDrawLibrary.new(t.readFile)
		local count = 0
		for line in (listing :: string):gmatch("[^\r\n]+") do
			local id, desc = line:match("^([^|]+)|(.*)$")
			if id == nil then
				continue
			end
			count += 1
			local ok, result = pcall(function(): string
				local mesh = flattenMesh(library, id .. ".dat")
				if mesh == nil then
					return "ERROR|no mesh"
				end
				local connections = findConnections(library, id .. ".dat", mesh)
				if connections == nil then
					return "ERROR|no connections result"
				end
				local counts: { [string]: number } = {}
				for _, connection in connections do
					counts[connection.type] = (counts[connection.type] or 0) + 1
				end
				counts["DerivedSocket"] = #deriveSockets(connections, mesh)
				local pieces = {}
				for kind, n in counts do
					if n > 0 then
						table.insert(pieces, `{kind}={n}`)
					end
				end
				table.sort(pieces)
				local size = mesh.boundsMax - mesh.boundsMin
				return `{table.concat(pieces, ",")}|{math.round(size.X)}x{math.round(size.Y)}x{math.round(size.Z)}|tris={#mesh.triangles}`
			end)
			t.log(`AUDIT|{id}|{desc}|{if ok then result else "ERROR|" .. tostring(result)}`)
			if count % 100 == 0 then
				task.wait()
			end
		end
		t.log(`AUDIT DONE: {count} parts`)
	end)
end
